name: Update Dotfiles (OMZ & Neovim Plugins)
on:
  workflow_dispatch: # 允许手动触发
  # schedule:
    # - cron: '0 0 * * 0'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dotfiles repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          submodules: 'recursive'

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: 'stable'

      - name: Update Neovim Plugins (Lazy)
        run: |
          echo "Bootstrapping lazy.nvim..."
          nvim --headless +qa

          echo "Updating Neovim plugins with Lazy..."
          nvim --headless "+Lazy! update" +qa
          
      - name: Update all submodules to the latest commit
        run: |
          git submodule update --remote --recursive
      - name: Create Pull Request if changes were found
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Automated submodule updates"
          committer: "GitHub Actions Bot <actions@github.com>"
          author: "GitHub Actions Bot <actions@github.com>"
          
          title: "[Bot] Update Submodules"
          body: |
            This is an auto-generated PR to update the submodules in the dotfiles repository.
            
            - Oh-My-Zsh
            - Neovim plugins
            - Other submodules
            
            Please review the changes and merge if they are acceptable.
          
          branch: "bot/auto-update-dotfiles"
          
          labels: |
            automated pr
            dependencies
          
          base: main
